server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://localhost:3306/information_schema?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#  jackson:
#    default-property-inclusion: non_null #返回时过滤掉null
  thymeleaf:
    prefix: classpath:/templates
    enabled: false
    encoding: utf-8
    mode: HTML
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.prac.onlinesql.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl