server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://localhost:3306/information_schema?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null #返回时过滤掉null
  thymeleaf:
    prefix: classpath:/templates
    enabled: false
    encoding: utf-8
    mode: HTML
